name: _job_build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

permissions:
  contents: write

jobs:
  proton:
    name: Build ${{ inputs.name }} (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-latest
          - arch: x86_64
            distro: ubuntu-latest
    env:
      BUILD_NAME: phlogiston-${{ inputs.name }}-${{ matrix.arch }}
    steps:
      - name: Cleanup disk space
        uses: endersonmenezes/free-disk-space@v4
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_codeql: true
          remove_docker_images: true
          remove_swap: true
          remove_packages: |
            azure-cli google-cloud-cli google-chrome-stable firefox microsoft-edge-stable
            postgresql* mysql* php* temurin-* *llvm* clang* mono-devel powershell dotnet-sdk-*
          remove_folders: |
            /usr/share/swift /usr/share/miniconda /usr/local/lib/node_modules
            /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia*
            /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle /usr/share/az*
            /usr/local/.ghcup

      - name: Prepare host
        run: sudo apt update && sudo apt-get install -y ccache fontforge-nox

      - name: Set up ARM emulation
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Restore cache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.ccache
          key: ccache-proton-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            ccache-proton-${{ matrix.arch }}-

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: false

      - name: Patch
        run: |
          git submodule update --init --filter=tree:0 --recursive
          # apply proton-ge-custom & Phlogiston patches
          ./patches/protonprep-valve-staging.sh || true
          # strip binaries at compile time to save space in the runner
          patch -Np1 -i ./.github/patches/0001-build-strip-binaries-early.patch
          mkdir ./build

      - name: Configure
        working-directory: ./build
        run: |
          ../configure.sh --build-name="$BUILD_NAME" --target-arch=${{ matrix.arch == 'aarch64' && 'arm64' || matrix.arch }} --container-engine=docker

      - name: Make ${{ env.BUILD_NAME }}
        working-directory: ./build
        run: |
          make -j$(nproc) redist

      - name: Save cache
        id: ccache-save
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}

      - name: Upload artifact ${{ env.BUILD_NAME }}.tar.gz
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.BUILD_NAME }}.tar.gz
          path: ./build/${{ env.BUILD_NAME }}.tar.gz

      - name: Upload artifact ${{ env.BUILD_NAME }}.sha512sum
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.BUILD_NAME }}.sha512sum
          path: ./build/${{ env.BUILD_NAME }}.sha512sum
